# This is autogenerated test suite file for sharp testing
import os
import pytest

@pytest.mark.test_id(29)
def test_my_test_case_5(ado_config, test_run_id, test_result_id):
	"""
	My test case description
	Details:{'configuration': {'name': 'my_config'}, 'description': 'My test case description', 'id': 29, 'name': 'my_test_case_5'}

	Args:
		ado_config: The ADO configuration.
		test_run_id: The ID of the test run.
		test_result_id: The ID of the test result.

	Returns:
		None
	"""
	work_item_id=29
	test_case_description="My test case description"
	print("ado_config:", ado_config)
	print("test_run_id:", test_run_id)
	print("test_result_id:", test_result_id)
	assert True


@pytest.mark.test_id(30)
def test_my_test_case_4(ado_config, test_run_id, test_result_id):
	"""
	My test case description
	Details:{'configuration': {'name': 'my_config'}, 'description': 'My test case description', 'id': 30, 'name': 'my_test_case_4'}

	Args:
		ado_config: The ADO configuration.
		test_run_id: The ID of the test run.
		test_result_id: The ID of the test result.

	Returns:
		None
	"""
	work_item_id=30
	test_case_description="My test case description"
	print("ado_config:", ado_config)
	print("test_run_id:", test_run_id)
	print("test_result_id:", test_result_id)
	assert True

