# This is autogenerated test suite file for sharp testing
import os
import pytest

@pytest.mark.test_id(27)
def test_my_test_case_2(ado_config, test_run_id, test_result_id):
	"""
	My test case description
	Details:{'configuration': {'name': 'my_config'}, 'description': 'My test case description', 'id': 27, 'name': 'my_test_case_2'}

	Args:
		ado_config: The ADO configuration.
		test_run_id: The ID of the test run.
		test_result_id: The ID of the test result.

	Returns:
		None
	"""
	work_item_id=27
	test_case_description="My test case description"
	print("ado_config:", ado_config)
	print("test_run_id:", test_run_id)
	print("test_result_id:", test_result_id)
	assert True


@pytest.mark.test_id(28)
def test_my_test_case_3(ado_config, test_run_id, test_result_id):
	"""
	My test case description
	Details:{'configuration': {'name': 'my_config'}, 'description': 'My test case description', 'id': 28, 'name': 'my_test_case_3'}

	Args:
		ado_config: The ADO configuration.
		test_run_id: The ID of the test run.
		test_result_id: The ID of the test result.

	Returns:
		None
	"""
	work_item_id=28
	test_case_description="My test case description"
	print("ado_config:", ado_config)
	print("test_run_id:", test_run_id)
	print("test_result_id:", test_result_id)
	assert True

